// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuA9AO1kAdtnP04tQQC3b8A53_kem9QGE',
    appId: '1:110059837900:web:ee8384906c24ee9d1f6569',
    messagingSenderId: '110059837900',
    projectId: 'seyra-92f01',
    authDomain: 'seyra-92f01.firebaseapp.com',
    storageBucket: 'seyra-92f01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARs3VVHOr3FOfg0usHc2YkDOFMJyVanwU',
    appId: '1:110059837900:android:04b3a51e1b327be71f6569',
    messagingSenderId: '110059837900',
    projectId: 'seyra-92f01',
    storageBucket: 'seyra-92f01.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc2O74lyBL65P1O5VUrVqL8X5EQQa3wl4',
    appId: '1:110059837900:ios:006424620359b3f41f6569',
    messagingSenderId: '110059837900',
    projectId: 'seyra-92f01',
    storageBucket: 'seyra-92f01.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuA9AO1kAdtnP04tQQC3b8A53_kem9QGE',
    appId: '1:110059837900:web:51179a917089b9011f6569',
    messagingSenderId: '110059837900',
    projectId: 'seyra-92f01',
    authDomain: 'seyra-92f01.firebaseapp.com',
    storageBucket: 'seyra-92f01.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc2O74lyBL65P1O5VUrVqL8X5EQQa3wl4',
    appId: '1:110059837900:ios:bf48aa8a3635fdf51f6569',
    messagingSenderId: '110059837900',
    projectId: 'seyra-92f01',
    storageBucket: 'seyra-92f01.firebasestorage.app',
    iosBundleId: 'com.seyra.app',
  );
}
